[package]
name = "Craftable Bandage"
homepage = "https://github.com/amaliegay/mwse-modding-tutorial"
authors = ["Amalie"]
version = "1.0.0"

[dependencies]
assets = ["MWSE/mods/Amalie/craftableBandage"]

[dependencies.mwse]
buildnumber = 3238

[dependencies.mods."OAAB_Data"]
version = "^2.1.9"
url = "https://www.nexusmods.com/morrowind/mods/49042"

[dependencies.mods."Ashfall"]
version = "^3.10.0"
url = "https://www.nexusmods.com/morrowind/mods/49057"

[dependencies.mods."The Crafting Framework"]
version = "^1.12.0"
url = "https://www.nexusmods.com/morrowind/mods/51009"

[dependencies.mods."Skills Module"]
mwse-module = "OtherSkills"
url = "https://www.nexusmods.com/morrowind/mods/46034"
