site_name: MWSE Modding Tutorial - Based Morrowind Modding now using Lua!
site_description: Learn to use MWSE-Lua in this tutorial for beginners! You will learn the basics of MWSE-Lua and make a MWSE-Lua mod step-by-step.
site_author: Amalie

repo_url: https://github.com/dev-chenxing/mwse-modding-tutorial/
repo_name: dev-chenxing/mwse-modding-tutorial

theme:
  name: material
  logo: assets/1200px-Lua-logo-nolabel-tutorial.png
  favicon: assets/1200px-Lua-logo-nolabel-tutorial.png
  custom_dir: overrides
  features: 
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: amber
      accent: indigo
    - scheme: slate
      toggle: 
        icon: material/weather-sunny
        name: Switch to light mode
      primary: indigo
      accent: amber

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
 - search

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/
    - icon: fontawesome/brands/github
      link: https://github.com/dev-chenxing

